logging:
  #日志存储地址
  file: "logs/app-client.log"
info:
  name : "App 后端接口"

server:
  #端口号
  port: 8888
  context-path: /
  #address: client1.com

##mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cc3?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  #jpa
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  show-sql: true
  #这是啥，我也不知道哎
  jackson:
    serialization:
      indent_output: true


 
 
